#!/bin/sh

adb shell "run-as com.transistorsoft.backgroundgeolocation.capacitor cat /data/user/0/com.transistorsoft.backgroundgeolocation.capacitor/databases/transistor_logback.db" > transistor_logback.db

